Tidy up pom.xml and roll back kafka to 3.3.2
3.4.0 introduced some weird binary incompatibility which makes the tests
fail:

java.lang.NoSuchMethodError: 'void org.apache.kafka.common.requests.JoinGroupResponse.<init>(org.apache.kafka.common.message.JoinGroupResponseData)'